# Generated by Django 4.2.1 on 2023-06-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizator", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id_category", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=100)),
            ],
        ),
    ]
