# Generated by Django 4.2.1 on 2023-06-09 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizator", "0002_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id_event", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("subtitle", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("main_img", models.ImageField(upload_to="event_images/")),
                ("thumbnail", models.ImageField(upload_to="event_thumbnails/")),
                ("licence", models.TextField(max_length=100)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizator.category",
                    ),
                ),
                (
                    "organism",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizator.organism",
                    ),
                ),
            ],
        ),
    ]
