# Generated by Django 4.2.1 on 2023-06-09 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizator", "0003_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organizator",
            fields=[
                ("id_organizator", models.AutoField(primary_key=True, serialize=False)),
                ("firstname", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_num", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=100)),
                ("is_admin", models.BooleanField(default=False)),
                (
                    "organism",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizator.organism",
                    ),
                ),
            ],
        ),
    ]
