# Generated by Django 4.2.1 on 2023-06-09 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizator", "0004_organizator"),
    ]

    operations = [
        migrations.CreateModel(
            name="PricingPlan",
            fields=[
                ("id_plan", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("tickets_available", models.IntegerField()),
                ("description", models.TextField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizator.event",
                    ),
                ),
            ],
        ),
    ]
