# Generated by Django 4.2.1 on 2023-06-09 00:41

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id_user", models.AutoField(primary_key=True, serialize=False)),
                ("firstname", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("username", models.CharField(max_length=100, unique=True)),
                ("date_of_birth", models.DateField()),
                (
                    "phone_num",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                ("password", models.CharField(max_length=100)),
                ("zipcode", models.IntegerField()),
                ("city", models.CharField(max_length=100)),
            ],
        ),
    ]
